CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=50

CONFIG_ZMK_MACRO_DEFAULT_TAP_MS=2
CONFIG_ZMK_MACRO_DEFAULT_WAIT_MS=2

#CONFIG_ZMK_USB_LOGGING=y
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2000
